/**
 * Jacquard's CPU half, PORTED to JavaScript for the browser demo.
 *
 * This is not the plugin's code. It is a hand translation, function for
 * function, of
 *
 *   source/Controls.cpp   OptionIndex, Ends, Picks, ThreadAspect, MaxFloat,
 *                         Shuttles, Zoom
 *   source/Palette.cpp    ToLinear, ToEncoded, Fixed, KMeans::Update (the
 *                         farthest-point-seeded, warm-started k-means)
 *   source/Weave.cpp      Coverage, Repeat, Family, WarpUp, LatticeStep
 *   source/Encoder.cpp    the exact row programme and its colour bound
 *                         (SolveRow, without the greedy negative control)
 *   source/Loom.cpp       Weave: the encoding table, tone to structure, the
 *                         integer costs, the memory terms, the forbidden
 *                         crossings, the carry
 *
 * and ONLY A READER CHECKS IT. jqtest --optimal, --floats, --shuttle and the
 * rest prove the C++ and have never heard of this file. What was measured
 * against the C++ once, and how closely it agreed, is in AGENTS.md under
 * "The browser demo". Change one of those C++ files and change this one by
 * hand, with the same care.
 *
 * The one block that is NOT hand-written is the generated block below: the
 * constants of Loom.h, Controls.h and Palette.h, the swatch cards and the
 * option names, lifted out of the C++ by demo/tools/sync_shaders.py and held to
 * it by demo/tools/check_shaders.py (which tools/verify.sh runs).
 *
 * ---------------------------------------------------------- the arithmetic
 *
 * The C++ does its colour arithmetic in 32-bit float. JavaScript's numbers are
 * doubles, so every float operation here is wrapped in Math.fround — one
 * rounding per operation, as the C++ source reads. That is exactly what the
 * plugin's Intel slice does. The Apple Silicon slice is compiled by clang with
 * -ffp-contract=on and fuses some multiply-adds (the squared distances, the
 * mixtures, the luminance, the table interpolation), which rounds once where
 * this rounds twice; so on the rare crossing whose choice sits on a knife edge
 * the two can differ, and the error carried down the cloth can carry that
 * difference on. powf is the platform's in the plugin and Math.pow rounded to
 * float here. The costs themselves are integers in both, and a JavaScript
 * double holds every one of them exactly (a pick's total stays far below
 * 2^53), so the programme's answer for a given table is the same answer.
 *
 * What is deliberately not ported: the Perturb test hooks, the forced
 * structure and the greedy weaver (negative controls for the harness, always
 * at rest in the plugin), and the `observe` callback.
 */

const f32 = Math.fround;

//=== BEGIN GENERATED by demo/tools/sync_shaders.py (constants) from source/ -- do not edit by hand.
// source/Loom.h
const LOOM_H = {
  kCostScale: 65536.0,
  kTie: 1024,
  kLattice: 512,
  kCarry: 1.0,
  kCarryLimit: 0.5,
  kHoldLift: 2048,
  kHoldShuttle: 384,
  kHoldStructure: 256,
};
// source/Controls.h
export const CONTROLS_H = {
  kEndsMin: 16,
  kEndsMax: 320,
  kEndsDefault: 160,
  kPicksMax: 320,
  kMaxFloatMin: 2,
  kMaxFloatMax: 16,
  kMaxFloatDefault: 10,
  kShuttlesMin: 2,
  kShuttlesMax: 8,
  kShuttlesDefault: 6,
};
// source/Palette.h
const PALETTE_H = {
  kMaxShuttles: 8,
};
// source/Palette.cpp: the swatch cards, sRGB.
const HERITAGE_SWATCHES = [[0.10, 0.09, 0.09], [0.90, 0.85, 0.72], [0.66, 0.16, 0.14], [0.14, 0.22, 0.42], [0.86, 0.72, 0.26], [0.28, 0.42, 0.24], [0.42, 0.28, 0.18], [0.84, 0.52, 0.52]];
const BRIGHT_SWATCHES = [[0.05, 0.05, 0.06], [0.96, 0.96, 0.94], [0.86, 0.10, 0.12], [0.08, 0.22, 0.78], [0.98, 0.82, 0.08], [0.08, 0.62, 0.26], [0.82, 0.16, 0.60], [0.10, 0.70, 0.82]];
// The option lists: Palette.cpp SourceName, Weave.cpp ModeName.
export const SOURCE_NAMES = ['Clip', 'Heritage Dyes', 'Mono', 'Bright'];
export const MODE_NAMES = ['Auto by Tone', 'Plain', 'Twill', 'Satin'];
//=== END GENERATED (constants)

//===========================================================================
// Controls.cpp
//===========================================================================

/// std::lround: halves away from zero (Math.round rounds -2.5 to -2).
function lround(x) {
  return x < 0 ? -Math.floor(-x + 0.5) : Math.floor(x + 0.5);
}

const clampInt = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

export function optionIndex(value, count) {
  return clampInt(lround(value), 0, count - 1);
}

export function ends(value) {
  return clampInt(lround(value), CONTROLS_H.kEndsMin, CONTROLS_H.kEndsMax);
}

export function picks(value, endCount, width, height, aspect) {
  const explicitPicks = lround(value);
  if (explicitPicks > 0) return Math.min(explicitPicks, CONTROLS_H.kPicksMax);
  if (width <= 0 || height <= 0) return 1;
  // An end is width / ends pixels wide; a pick aspect times that tall. Double.
  const p = (height * endCount) / (width * aspect);
  return clampInt(lround(p), 1, CONTROLS_H.kPicksMax);
}

export function threadAspect(value) {
  return 0.5 * Math.pow(4.0, clampInt(value, 0.0, 1.0));
}

export function maxFloat(value) {
  return clampInt(lround(value), CONTROLS_H.kMaxFloatMin, CONTROLS_H.kMaxFloatMax);
}

export function shuttles(value) {
  return clampInt(lround(value), CONTROLS_H.kShuttlesMin, CONTROLS_H.kShuttlesMax);
}

export function zoom(value) {
  return Math.pow(8.0, clampInt(value, 0.0, 1.0));
}

//===========================================================================
// Palette.cpp
//===========================================================================

export const MAX_SHUTTLES = PALETTE_H.kMaxShuttles;
export const K_CLIP = 0;
const K_HERITAGE = 1;
const K_MONO = 2;
const K_BRIGHT = 3;
export const SOURCE_COUNT = SOURCE_NAMES.length;

// The float literals, as the float the C++ compiler makes of each.
const F_0_04045 = f32(0.04045);
const F_12_92 = f32(12.92);
const F_0_055 = f32(0.055);
const F_1_055 = f32(1.055);
const F_2_4 = f32(2.4);
const F_0_0031308 = f32(0.0031308);
const F_INV_2_4 = f32(1 / F_2_4); // 1.0f / 2.4f, folded in float
const F_LUMA_R = f32(0.2126);
const F_LUMA_G = f32(0.7152);
const F_LUMA_B = f32(0.0722);

/// std::clamp on floats: v < lo ? lo : hi < v ? hi : v.
const clampF = (v, lo, hi) => (v < lo ? lo : hi < v ? hi : v);

export function toLinear(v) {
  v = clampF(v, 0, 1);
  return v <= F_0_04045 ? f32(v / F_12_92) : f32(Math.pow(f32(f32(v + F_0_055) / F_1_055), F_2_4));
}

export function toEncoded(v) {
  v = clampF(v, 0, 1);
  return v <= F_0_0031308 ? f32(F_12_92 * v) : f32(f32(F_1_055 * f32(Math.pow(v, F_INV_2_4))) - F_0_055);
}

/// Linear colours are [r, g, b] triples of floats.
function fromSwatch(s) {
  return [toLinear(f32(s[0])), toLinear(f32(s[1])), toLinear(f32(s[2]))];
}

function distance2(a, b) {
  const dr = f32(a[0] - b[0]);
  const dg = f32(a[1] - b[1]);
  const db = f32(a[2] - b[2]);
  return f32(f32(f32(dr * dr) + f32(dg * dg)) + f32(db * db));
}

function luma(c) {
  return f32(f32(f32(F_LUMA_R * c[0]) + f32(F_LUMA_G * c[1])) + f32(F_LUMA_B * c[2]));
}

/// A fixed swatch set's first K colours, in linear light.
export function fixed(source, count) {
  count = clampInt(count, 1, MAX_SHUTTLES);
  const out = [];
  for (let k = 0; k < count; k += 1) {
    if (source === K_MONO) {
      // Evenly spaced greys in the encoding, black to white.
      const v = count > 1 ? f32(k / (count - 1)) : 0.5;
      const l = toLinear(v);
      out.push([l, l, l]);
    } else if (source === K_BRIGHT) {
      out.push(fromSwatch(BRIGHT_SWATCHES[k]));
    } else {
      out.push(fromSwatch(HERITAGE_SWATCHES[k]));
    }
  }
  return out;
}

/// KMeans::Update. Lloyd's algorithm in linear light, warm-started from the
/// last frame's centres when K is unchanged; a cold start seeds by farthest
/// point from the median by luminance.
export class KMeans {
  constructor() {
    this.centres = [];
    this.coldStarts = 0;
  }

  reset() {
    this.centres = [];
  }

  update(rgba, count, k, sampleStep) {
    k = clampInt(k, 1, MAX_SHUTTLES);
    sampleStep = Math.max(1, sampleStep);

    const points = [];
    for (let i = 0; i < count; i += sampleStep) {
      const t = i * 4;
      points.push([rgba[t], rgba[t + 1], rgba[t + 2]]);
    }
    if (points.length === 0) {
      this.centres = [];
      for (let c = 0; c < k; c += 1) this.centres.push([f32(0.2), f32(0.2), f32(0.2)]);
      return;
    }

    let iterations = 3;
    if (this.centres.length !== k) {
      this.coldStarts += 1;
      iterations = 6;
      const lumas = points.map(luma);
      const byLuma = points.map((_, i) => i);
      // std::stable_sort by luminance; Array.prototype.sort is stable.
      byLuma.sort((a, b) => (lumas[a] < lumas[b] ? -1 : lumas[b] < lumas[a] ? 1 : 0));
      this.centres = [points[byLuma[Math.floor(byLuma.length / 2)]].slice()];
      const nearest = new Float32Array(points.length);
      for (let i = 0; i < points.length; i += 1) nearest[i] = distance2(points[i], this.centres[0]);
      while (this.centres.length < k) {
        let farthest = 0;
        for (let i = 1; i < points.length; i += 1) if (nearest[i] > nearest[farthest]) farthest = i;
        this.centres.push(points[farthest].slice());
        const back = this.centres[this.centres.length - 1];
        for (let i = 0; i < points.length; i += 1) nearest[i] = Math.min(nearest[i], distance2(points[i], back));
      }
    }

    const centres = this.centres;
    const sum = new Float64Array(k * 3);
    const members = new Int32Array(k);
    for (let iteration = 0; iteration < iterations; iteration += 1) {
      sum.fill(0);
      members.fill(0);
      let worst = f32(-1);
      let worstI = 0;
      for (let i = 0; i < points.length; i += 1) {
        let best = 0;
        let bestD = distance2(points[i], centres[0]);
        for (let c = 1; c < k; c += 1) {
          const d = distance2(points[i], centres[c]);
          if (d < bestD) {
            bestD = d;
            best = c;
          }
        }
        if (bestD > worst) {
          worst = bestD;
          worstI = i;
        }
        // Summed in double, as the C++ does.
        sum[best * 3] += points[i][0];
        sum[best * 3 + 1] += points[i][1];
        sum[best * 3 + 2] += points[i][2];
        members[best] += 1;
      }
      for (let c = 0; c < k; c += 1) {
        const m = members[c];
        if (m === 0) {
          // An empty shuttle takes the worst-served colour in the frame.
          centres[c] = points[worstI].slice();
          continue;
        }
        centres[c] = [f32(sum[c * 3] / m), f32(sum[c * 3 + 1] / m), f32(sum[c * 3 + 2] / m)];
      }
    }
  }
}

//===========================================================================
// Weave.cpp
//===========================================================================

const S = {
  warpSolid: 0, warpSatin: 1, twill31: 2, twill21: 3, plain: 4,
  twill22: 5, twill12: 6, twill13: 7, weftSatin: 8, weftSolid: 9,
};
export const STRUCTURE_COUNT = 10;
export const MODE_AUTO = 0;
const MODE_PLAIN = 1;
const MODE_TWILL = 2;
const MODE_SATIN = 3;
export const MODE_COUNT = MODE_NAMES.length;

/// Warp over `over` of a `repeat`, for the twills; zeros for anything else.
function twillShape(structure) {
  switch (structure) {
    case S.twill31: return [3, 4];
    case S.twill21: return [2, 3];
    case S.twill22: return [2, 4];
    case S.twill12: return [1, 3];
    case S.twill13: return [1, 4];
    default: return [0, 0];
  }
}

function repeatOf(structure) {
  switch (structure) {
    case S.warpSolid:
    case S.weftSolid: return 1;
    case S.warpSatin:
    case S.weftSatin: return 5;
    case S.plain: return 2;
    default: return twillShape(structure)[1];
  }
}

/// Weft coverage as num / den, in double (Weave.cpp's `double Coverage`).
function coverage(structure) {
  switch (structure) {
    case S.warpSolid: return 0 / 1;
    case S.weftSolid: return 1 / 1;
    case S.warpSatin: return 1 / 5;
    case S.weftSatin: return 4 / 5;
    case S.plain: return 1 / 2;
    default: {
      const [over, repeat] = twillShape(structure);
      return (repeat - over) / repeat;
    }
  }
}

function family(mode) {
  switch (mode) {
    case MODE_PLAIN: return [S.plain];
    case MODE_TWILL: return [S.twill31, S.twill22, S.twill13];
    case MODE_SATIN: return [S.warpSatin, S.weftSatin];
    default:
      // Auto: the solids at the ends, the satins next, the three- and
      // four-end twills in the midtones; plain and 3/1, 1/3 left out.
      return [S.warpSolid, S.warpSatin, S.twill21, S.twill22, S.twill12, S.weftSatin, S.weftSolid];
  }
}

/// Warp on top at end i, pick j (both absolute, non-negative). No Perturb.
function warpUp(structure, i, j) {
  switch (structure) {
    case S.warpSolid: return true;
    case S.weftSolid: return false;
    case S.warpSatin: return (i + 2 * j) % 5 !== 0;
    case S.weftSatin: return (i + 2 * j) % 5 === 0;
    case S.plain: return (i + j) % 2 === 0;
    default: {
      const [over, repeat] = twillShape(structure);
      return (i + j) % repeat < over;
    }
  }
}

function gcd(a, b) {
  while (b) [a, b] = [b, a % b];
  return a;
}

function latticeStep(period) {
  for (let s = 2; s <= period - 2; s += 1) if (gcd(s, period) === 1) return s;
  return 1;
}

//===========================================================================
// Encoder.cpp: the exact row programme.
//
// Costs are integers held in a Float64Array; kInfinite is Infinity, which
// compares the same way INT64_MAX / 4 does and is never added to.
//===========================================================================

const INF = Infinity;

class RowTable {
  resize(crossings, colours, limit) {
    this.n = crossings;
    this.colours = colours;
    this.maxFloat = limit;
    if (!this.cost || this.cost.length !== colours * crossings * 2) this.cost = new Float64Array(colours * crossings * 2);
    else this.cost.fill(0);
    if (!this.forbidden || this.forbidden.length !== crossings) this.forbidden = new Int8Array(crossings);
    this.forbidden.fill(-1);
  }
}

function runCap(table) {
  return table.maxFloat > 0 ? Math.min(table.maxFloat, table.n) : Math.max(table.n, 1);
}

let dpCur = new Float64Array(0);
let dpNxt = new Float64Array(0);
let dpFrom = new Uint16Array(0);

/// The programme for one colour: state (value, run 1..M) at v * M + r - 1.
/// Returns the cost and fills x.
function programme(table, c, x) {
  const n = table.n;
  const M = runCap(table);
  const cost = table.cost;
  const forbidden = table.forbidden;
  if (dpCur.length < 2 * M) {
    dpCur = new Float64Array(2 * M);
    dpNxt = new Float64Array(2 * M);
  }
  if (dpFrom.length < n * 2) dpFrom = new Uint16Array(n * 2);
  let cur = dpCur;
  let nxt = dpNxt;
  cur.fill(INF, 0, 2 * M);
  nxt.fill(INF, 0, 2 * M);
  dpFrom.fill(0, 0, n * 2);
  const from = dpFrom;
  const base = c * n * 2;

  for (let v = 0; v < 2; v += 1) if (forbidden[0] !== v) cur[v * M] = cost[base + v];

  for (let i = 1; i < n; i += 1) {
    // The cheapest run of each value ending at i - 1, and its length.
    let best0 = INF;
    let best1 = INF;
    let bestR0 = 0;
    let bestR1 = 0;
    for (let r = 0; r < M; r += 1) {
      const value = cur[r];
      if (value < best0) {
        best0 = value;
        bestR0 = r + 1;
      }
    }
    for (let r = 0; r < M; r += 1) {
      const value = cur[M + r];
      if (value < best1) {
        best1 = value;
        bestR1 = r + 1;
      }
    }

    nxt.fill(INF, 0, 2 * M);
    for (let u = 0; u < 2; u += 1) {
      if (forbidden[i] === u) continue;
      const here = cost[base + i * 2 + u];
      const other = u === 0 ? best1 : best0;
      // Start a run of u after a run of the other value.
      if (other < INF) {
        nxt[u * M] = other + here;
        from[i * 2 + u] = u === 0 ? bestR1 : bestR0;
      }
      // Extend a run of u that is still shorter than M.
      for (let r = 1; r < M; r += 1) {
        const previous = cur[u * M + r - 1];
        if (previous < INF) nxt[u * M + r] = previous + here;
      }
    }
    const t = cur;
    cur = nxt;
    nxt = t;
  }

  let total = INF;
  let endV = 0;
  let endR = 0;
  for (let v = 0; v < 2; v += 1) {
    for (let r = 0; r < M; r += 1) {
      if (cur[v * M + r] < total) {
        total = cur[v * M + r];
        endV = v;
        endR = r + 1;
      }
    }
  }
  if (total >= INF) return INF;

  // Walk back run by run.
  x.fill(0, 0, n);
  let i = n - 1;
  let v = endV;
  let r = endR;
  while (i >= 0) {
    const start = i - r + 1;
    for (let k = start; k <= i; k += 1) x[k] = v;
    if (start === 0) break;
    const previousR = from[start * 2 + v];
    i = start - 1;
    v = 1 - v;
    r = previousR;
  }
  return total;
}

/// SolveRow, the exact half: colours tried in order of a lower bound, stopping
/// when the bound reaches the best row found. The greedy weaver (the
/// harness's negative control) is not ported.
function solveRow(table, result) {
  result.colour = 0;
  result.cost = INF;
  result.feasible = false;
  result.programmesRun = 0;
  const n = table.n;
  const K = table.colours;
  if (n <= 0 || K <= 0) return result;
  if (!result.x || result.x.length !== n) result.x = new Uint8Array(n);
  if (!result.scratch || result.scratch.length !== n) result.scratch = new Uint8Array(n);

  const bound = new Float64Array(K);
  for (let c = 0; c < K; c += 1) {
    let sum = 0;
    for (let i = 0; i < n; i += 1) {
      let cheapest = INF;
      for (let v = 0; v < 2; v += 1) {
        if (table.forbidden[i] !== v) cheapest = Math.min(cheapest, table.cost[(c * n + i) * 2 + v]);
      }
      sum += cheapest;
    }
    bound[c] = sum;
  }
  const order = [];
  for (let c = 0; c < K; c += 1) order.push(c);
  order.sort((a, b) => (bound[a] < bound[b] ? -1 : bound[b] < bound[a] ? 1 : 0)); // stable

  const x = result.scratch;
  for (const c of order) {
    if (bound[c] >= result.cost) break; // no remaining colour can beat the row found
    const cost = programme(table, c, x);
    result.programmesRun += 1;
    if (cost < result.cost) {
      result.colour = c;
      result.x.set(x);
      result.cost = cost;
      result.feasible = true;
    }
  }
  return result;
}

//===========================================================================
// Loom.cpp
//===========================================================================

const K_COST_SCALE = f32(LOOM_H.kCostScale); // static_cast< float >( kCostScale )
const K_TIE = LOOM_H.kTie;
const K_LATTICE = LOOM_H.kLattice;
const K_CARRY = f32(LOOM_H.kCarry);
const K_CARRY_LIMIT = f32(LOOM_H.kCarryLimit);
const K_HOLD_LIFT = LOOM_H.kHoldLift;
const K_HOLD_SHUTTLE = LOOM_H.kHoldShuttle;
const K_HOLD_STRUCTURE = LOOM_H.kHoldStructure;
const F_HALF = f32(0.5);
const F_QUARTER = f32(0.25);

/// Loom.cpp's `Encoding`: the sRGB encoding by table, 4096 intervals on
/// [0, 1], linearly interpolated.
const ENC_SIZE = 4096;
const ENC_TABLE = new Float32Array(ENC_SIZE + 1);
for (let k = 0; k <= ENC_SIZE; k += 1) ENC_TABLE[k] = toEncoded(f32(k / ENC_SIZE));

function enc(v) {
  v = f32(clampF(v, 0, 1) * ENC_SIZE);
  const k = Math.min(Math.trunc(v), ENC_SIZE - 1);
  const f = f32(v - k);
  return f32(ENC_TABLE[k] + f32(f32(ENC_TABLE[k + 1] - ENC_TABLE[k]) * f));
}

/// A squared error (never negative) to cost units, rounded half up, through
/// a float as the C++ does it.
function quantise(squaredError) {
  return Math.trunc(f32(f32(squaredError * K_COST_SCALE) + F_HALF));
}

const LANES = 8;
const MAX_REPEAT = 5;

export function emptyCloth() {
  return {
    ends: 0, picks: 0, lift: new Uint8Array(0), weft: new Uint8Array(0), structure: new Uint8Array(0),
    shuttleCount: 0, mode: -1, forcedStructure: -1, cost: 0, infeasiblePicks: 0, remembered: false, programmes: 0,
  };
}

/**
 * loom::Weave. `means` is ends x picks linear RGBA floats (stride 4), row 0 the
 * top pick. `s` is { ends, picks, warp: [r,g,b] linear, shuttles: [[r,g,b]...],
 * maxFloat, mode }. `previous` is last frame's cloth, remembered when it is
 * the same grid, shuttle count and mode. Returns a new cloth.
 */
export function weave(means, s, previous = null) {
  const n = s.ends;
  const K = clampInt(s.shuttles.length, 1, MAX_SHUTTLES);
  const M = s.maxFloat <= 0 ? 0 : s.maxFloat;
  const forcedStructure = -1;

  const out = emptyCloth();
  out.ends = n;
  out.picks = s.picks;
  out.lift = new Uint8Array(n * s.picks);
  out.weft = new Uint8Array(s.picks);
  out.structure = new Uint8Array(n * s.picks);
  out.shuttleCount = K;
  out.mode = s.mode;
  out.forcedStructure = forcedStructure;
  if (n <= 0 || s.picks <= 0 || !s.shuttles) return out;

  const remember = previous !== null && previous !== out && previous.ends === n && previous.picks === s.picks
    && previous.shuttleCount === K && previous.mode === s.mode && previous.forcedStructure === forcedStructure
    && previous.lift.length === out.lift.length;
  out.remembered = remember;

  //-----------------------------------------------------------------
  // Per frame: the family, and every (structure, shuttle) mixture in
  // linear light, encoded.
  //-----------------------------------------------------------------
  const fam = family(s.mode);
  const levels = fam.length;

  const W = s.warp;
  const mixEncoded = new Float32Array(levels * K * 3);
  for (let l = 0; l < levels; l += 1) {
    const f = f32(coverage(fam[l]));
    const g = f32(1 - f);
    for (let c = 0; c < K; c += 1) {
      const weft = s.shuttles[c];
      const at = (l * K + c) * 3;
      for (let ch = 0; ch < 3; ch += 1) {
        const m = f32(f32(f * weft[ch]) + f32(g * W[ch]));
        mixEncoded[at + ch] = toEncoded(m);
      }
    }
  }

  const warpEncoded = [toEncoded(W[0]), toEncoded(W[1]), toEncoded(W[2])];
  const weftEncoded = [];
  for (let c = 0; c < K; c += 1) weftEncoded.push([toEncoded(s.shuttles[c][0]), toEncoded(s.shuttles[c][1]), toEncoded(s.shuttles[c][2])]);

  // The range the threads span, per channel, on the encoding.
  const lo = warpEncoded.slice();
  const hi = warpEncoded.slice();
  for (const w of weftEncoded) {
    for (let ch = 0; ch < 3; ch += 1) {
      lo[ch] = Math.min(lo[ch], w[ch]);
      hi[ch] = Math.max(hi[ch], w[ch]);
    }
  }

  //-----------------------------------------------------------------
  // The picks, top to bottom.
  //-----------------------------------------------------------------
  const table = new RowTable();
  table.resize(n, K, M);
  const chosen = new Uint8Array(K * n);
  const carry = new Float32Array(n * 3);
  const residual = new Float32Array(n * 3);
  const targetEncoded = new Float32Array(n * 3);
  const lattice = new Uint8Array(n);
  const pattern = new Uint8Array(levels * n);
  const repeat = new Int32Array(levels);
  const tiles = new Uint8Array(levels * MAX_REPEAT * MAX_REPEAT);
  for (let l = 0; l < levels; l += 1) {
    const R = repeatOf(fam[l]);
    repeat[l] = R;
    for (let jj = 0; jj < R; jj += 1) {
      for (let ii = 0; ii < R; ii += 1) tiles[(l * MAX_REPEAT + jj) * MAX_REPEAT + ii] = warpUp(fam[l], ii, jj) ? 1 : 0;
    }
  }
  // The mixtures again, as three eight-lane arrays a shuttle, padded far away.
  const lanes = new Float32Array(K * 3 * LANES).fill(1.0e6);
  for (let c = 0; c < K; c += 1) {
    for (let l = 0; l < levels; l += 1) {
      const at = (l * K + c) * 3;
      lanes[(c * 3 + 0) * LANES + l] = mixEncoded[at];
      lanes[(c * 3 + 1) * LANES + l] = mixEncoded[at + 1];
      lanes[(c * 3 + 2) * LANES + l] = mixEncoded[at + 2];
    }
  }
  const step = M > 0 ? latticeStep(M + 1) : 1;
  const columnValue = new Uint8Array(n);
  const columnRun = new Int32Array(n);
  const distance = new Float32Array(LANES);
  const row = {};

  for (let j = 0; j < s.picks; j += 1) {
    for (let i = 0; i < n; i += 1) {
      const t = (j * n + i) * 4;
      for (let ch = 0; ch < 3; ch += 1) {
        targetEncoded[i * 3 + ch] = f32(enc(means[t + ch]) + f32(K_CARRY * carry[i * 3 + ch]));
      }
    }
    // The tie lattice along this pick: ( i + s j ) mod ( M + 1 ) == 0.
    for (let i = 0; i < n; i += 1) lattice[i] = M > 0 && (i + step * j) % (M + 1) === 0 ? 1 : 0;

    // Each structure's pattern along this pick, from its tiled repeat.
    for (let l = 0; l < levels; l += 1) {
      const R = repeat[l];
      const line = (l * MAX_REPEAT + (j % R)) * MAX_REPEAT;
      for (let i = 0, ii = 0; i < n; i += 1, ii = ii + 1 === R ? 0 : ii + 1) pattern[l * n + i] = tiles[line + ii];
    }

    for (let c = 0; c < K; c += 1) {
      const laneR = (c * 3 + 0) * LANES;
      const laneG = (c * 3 + 1) * LANES;
      const laneB = (c * 3 + 2) * LANES;
      const weftE = weftEncoded[c];
      const shuttleHold = remember && previous.weft[j] !== c ? K_HOLD_SHUTTLE : 0;
      for (let i = 0; i < n; i += 1) {
        // Tone to structure: the mixture nearest the target, on the
        // encoding. Ties go to the lower coverage.
        const ter = targetEncoded[i * 3];
        const teg = targetEncoded[i * 3 + 1];
        const teb = targetEncoded[i * 3 + 2];
        for (let l = 0; l < LANES; l += 1) {
          const dr = f32(ter - lanes[laneR + l]);
          const dg = f32(teg - lanes[laneG + l]);
          const db = f32(teb - lanes[laneB + l]);
          distance[l] = f32(f32(f32(dr * dr) + f32(dg * dg)) + f32(db * db));
        }
        let best = 0;
        let bestD = distance[0];
        for (let l = 1; l < levels; l += 1) {
          if (distance[l] < bestD) {
            bestD = distance[l];
            best = l;
          }
        }
        const cell = j * n + i;
        let E = quantise(bestD);
        if (remember && fam[best] !== previous.structure[cell]) {
          // Keep last frame's structure while it is nearly as good.
          for (let l = 0; l < levels; l += 1) {
            if (fam[l] === previous.structure[cell]) {
              const kept = quantise(distance[l]);
              if (kept <= E + K_HOLD_STRUCTURE) {
                best = l;
                E = kept;
              }
            }
          }
        }
        const d = pattern[best * n + i];
        const shown = d === 1 ? weftE : warpEncoded;
        const er = f32(ter - shown[0]);
        const eg = f32(teg - shown[1]);
        const eb = f32(teb - shown[2]);
        const tie = K_TIE + quantise(f32(f32(f32(er * er) + f32(eg * eg)) + f32(eb * eb))) - (lattice[i] ? K_LATTICE : 0);
        const at = (c * n + i) * 2;
        table.cost[at + d] = E + shuttleHold;
        table.cost[at + 1 - d] = E + tie + shuttleHold;
        if (remember) table.cost[at + 1 - previous.lift[cell]] += K_HOLD_LIFT;
        chosen[c * n + i] = best;
      }
    }

    for (let i = 0; i < n; i += 1) table.forbidden[i] = M > 0 && columnRun[i] >= M ? columnValue[i] : -1;

    solveRow(table, row);
    out.cost += row.cost;
    out.programmes += row.programmesRun;
    if (!row.feasible) out.infeasiblePicks += 1;

    const c = row.colour;
    out.weft[j] = c;
    for (let i = 0; i < n; i += 1) {
      // `row.x.empty() ? 0 : row.x[ i ]`: x is only written by a feasible row.
      const x = row.feasible ? row.x[i] : 0;
      const cell = j * n + i;
      const level = chosen[c * n + i];
      out.lift[cell] = x;
      out.structure[cell] = fam[level];

      if (columnRun[i] > 0 && columnValue[i] === x) columnRun[i] += 1;
      else {
        columnValue[i] = x;
        columnRun[i] = 1;
      }

      // What the crossing still owes, on the encoding: the target clamped to
      // the threads' own range, per channel, less the mixture, bounded.
      const at = (level * K + c) * 3;
      for (let ch = 0; ch < 3; ch += 1) {
        const te = targetEncoded[i * 3 + ch];
        residual[i * 3 + ch] = clampF(f32(clampF(te, lo[ch], hi[ch]) - mixEncoded[at + ch]), -K_CARRY_LIMIT, K_CARRY_LIMIT);
      }
    }

    // Spread 1/4, 1/2, 1/4 to the next pick, renormalised at the selvedges.
    for (let i = 0; i < n; i += 1) {
      let w = F_HALF;
      let r = f32(F_HALF * residual[i * 3]);
      let g = f32(F_HALF * residual[i * 3 + 1]);
      let b = f32(F_HALF * residual[i * 3 + 2]);
      for (const side of [i - 1, i + 1]) {
        if (side >= 0 && side < n) {
          w = f32(w + F_QUARTER);
          r = f32(r + f32(F_QUARTER * residual[side * 3]));
          g = f32(g + f32(F_QUARTER * residual[side * 3 + 1]));
          b = f32(b + f32(F_QUARTER * residual[side * 3 + 2]));
        }
      }
      carry[i * 3] = f32(r / w);
      carry[i * 3 + 1] = f32(g / w);
      carry[i * 3 + 2] = f32(b / w);
    }
  }
  return out;
}
