/**
 * Jacquard — browser demo.
 *
 * The picture woven on a jacquard loom. The one idea, from `source/Jacquard.h`:
 * at every crossing of a cloth one thread is on top, the warp running down or
 * the weft running across, and a jacquard head can lift every warp end on its
 * own — but colour comes from threads (one warp colour, one weft colour a pick
 * from the shuttles loaded), no float may run past Max Float, and tone is
 * carried by weave structure. So the encoder is an optimiser under
 * constraints, solved exactly pick by pick down the cloth.
 *
 * Like teletext, this plugin is **not only a shader**, and the two halves of
 * the page are not equally faithful:
 *
 *   The shaders are the plugin's. `VERTEX_BODY`, `CELLS_BODY` and `RENDER_BODY`
 *   below are `kVertexBody`, `kCellsBody` and `kRenderBody` from
 *   `source/Shaders.cpp`, spliced in by `demo/tools/sync_shaders.py` with their
 *   tabs and comments, and assembled with the same `#version 410 core` line
 *   `shaders::assemble` prepends. `demo/tools/check_shaders.py` compares them
 *   character for character and `tools/verify.sh` runs it.
 *
 *   The CPU half is a PORT, in `loom.js` — Controls.cpp, Palette.cpp (the
 *   k-means), Weave.cpp, Encoder.cpp (the exact row programme) and Loom.cpp —
 *   and the frame sequence below is `Jacquard::ProcessOpenGL`'s. Nothing checks
 *   a port but a reader; jqtest checks the C++ and has never heard of this page.
 *
 * ------------------------------------------------------ the readback
 *
 * The plugin reads the Ends x Picks crossing means back with `glGetTexImage(
 * …, GL_FLOAT )` every frame, runs the palette and the loom on the CPU, and
 * uploads an Ends x Picks RG8 lift texture. The page does exactly that: one
 * `readPixels` of an RGBA32F target as FLOAT (EXT_color_buffer_float), the
 * loom in JavaScript, and an RG8 upload. It stalls the pipeline where the
 * plugin's does.
 *
 * ------------------------------------------------------- what is missing
 *
 * **Nothing audio**: Jacquard has no audio path. **No clock**: the plugin reads
 * no time, so the page's clock only moves the clip. **The About block is
 * absent**, as on every page in this suite. **The four integer controls are
 * dropdowns**: the kit has no integer control, so Ends, Picks, Max Float and
 * Shuttles are dropdowns of every value in the plugin's range, as teletext's
 * and copperlist's are. The Perturb and forced-structure test hooks are at
 * rest (0 and -1), as the shipped plugin has them.
 */

import { mountDemo } from './vendor/demo.js';
import { Program, PassBuffer, bindTexture } from './vendor/gl.js';
import * as L from './loom.js';

//=== BEGIN GENERATED by demo/tools/sync_shaders.py (shaders) from source/Shaders.cpp -- do not edit by hand.
const VERSION = '#version 410 core\n';

const VERTEX_BODY = `
layout( location = 0 ) in vec4 vPosition;
layout( location = 1 ) in vec2 vUV;

out vec2 uv;

void main()
{
	gl_Position = vPosition;
	uv = vUV;
}
`;

const CELLS_BODY = `
uniform sampler2D InputTexture;
uniform ivec2 InputSize;   //the picture in texels (not the hardware size)
uniform ivec2 Grid;        //ends, picks

in vec2 uv;
out vec4 fragColor;

float toLinear( float v )
{
	return v <= 0.04045 ? v / 12.92 : pow( ( v + 0.055 ) / 1.055, 2.4 );
}

void main()
{
	ivec2 crossing = ivec2( floor( gl_FragCoord.xy ) );   //end, pick (top-down)
	vec2 span = vec2( InputSize ) / vec2( Grid );

	//The crossing's rectangle, y down, and the pixels whose centres lie in
	//it: p + 0.5 in [ a, b ) is p in [ ceil( a - 0.5 ), ceil( b - 0.5 ) ).
	vec2 a = vec2( crossing ) * span;
	vec2 b = vec2( crossing + 1 ) * span;
	ivec2 p0 = clamp( ivec2( ceil( a - 0.5 ) ), ivec2( 0 ), InputSize );
	ivec2 p1 = clamp( ivec2( ceil( b - 0.5 ) ), ivec2( 0 ), InputSize );
	p1 = max( p1, min( p0 + 1, InputSize ) );   //at least one tap

	//Past 16 a side the taps are strided.
	int sx = max( 1, ( p1.x - p0.x + 15 ) / 16 );
	int sy = max( 1, ( p1.y - p0.y + 15 ) / 16 );

	vec3 sum = vec3( 0.0 );
	float n  = 0.0;
	for( int y = p0.y; y < p1.y; y += sy )
	{
		int glY = InputSize.y - 1 - y;   //the texture's row 0 is the bottom
		for( int x = p0.x; x < p1.x; x += sx )
		{
			vec4 t = texelFetch( InputTexture, ivec2( x, glY ), 0 );
			sum += vec3( toLinear( t.r ), toLinear( t.g ), toLinear( t.b ) );
			n += 1.0;
		}
	}
	fragColor = vec4( sum / max( n, 1.0 ), 1.0 );
}
`;

const RENDER_BODY = `
uniform sampler2D Lift;
uniform sampler2D Source;
uniform vec2 MaxUV;
uniform ivec2 OutSize;
uniform ivec2 Grid;          //ends, picks
uniform vec3 Warp;           //linear
uniform vec3 Shuttle[ 8 ];   //linear
uniform int Shuttles;
uniform float Zoom;
uniform float Shading;
uniform float MixAmount;
uniform int Perturb;

in vec2 uv;
out vec4 fragColor;

//The light, from the upper left in screen space (y down), and the
//thread's lit profile scaled so a flat crossing of warp averages 1.
const vec3 kLight   = vec3( -0.45, -0.55, 0.70 );
const float kWidth  = 0.90;   //a thread's width, of its spacing
const float kDip    = 0.32;   //how far along a float its end dives under
const float kTwist  = 3.0;    //ply twists along one crossing
const float kGain   = 1.18;   //1 / the profile's mean, on a flat crossing

float encode( float v )
{
	v = clamp( v, 0.0, 1.0 );
	return v <= 0.0031308 ? 12.92 * v : 1.055 * pow( v, 1.0 / 2.4 ) - 0.055;
}

bool warpAt( ivec2 c )
{
	c = clamp( c, ivec2( 0 ), Grid - 1 );
	return texelFetch( Lift, c, 0 ).r > 0.5;
}

int weftOf( ivec2 c )
{
	return int( texelFetch( Lift, c, 0 ).g * 255.0 + 0.5 );
}

void main()
{
	vec4 source = texture( Source, uv * MaxUV );

	//This pixel's centre, top-down, through the zoom about the frame centre.
	vec2 p      = vec2( floor( gl_FragCoord.x ), float( OutSize.y ) - 1.0 - floor( gl_FragCoord.y ) ) + 0.5;
	vec2 centre = vec2( OutSize ) * 0.5;
	vec2 q      = centre + ( p - centre ) / Zoom;
	vec2 g      = q * vec2( Grid ) / vec2( OutSize );
	ivec2 cell  = clamp( ivec2( floor( g ) ), ivec2( 0 ), Grid - 1 );
	vec2 f      = clamp( g - vec2( cell ), 0.0, 1.0 );

	bool warpTop = warpAt( cell );
	int weft     = weftOf( cell );
	if( ( Perturb & 16 ) != 0 && ( cell.x & 1 ) == 1 )
		weft = ( weft + 1 ) % max( Shuttles, 1 );
	vec3 weftColour = Shuttle[ clamp( weft, 0, 7 ) ];
	vec3 colour     = warpTop ? Warp : weftColour;

	//Thread Shading fades out where a crossing is under a few pixels: the
	//profile there can only alias, and from that far the cloth is its colour.
	vec2 crossingPx = vec2( OutSize ) / vec2( Grid ) * Zoom;
	float amount    = Shading * smoothstep( 2.0, 6.0, min( crossingPx.x, crossingPx.y ) );

	vec3 cloth = colour;
	if( amount > 0.0 )
	{
		float across = warpTop ? f.x : f.y;
		float along  = warpTop ? f.y : f.x;
		ivec2 before = warpTop ? ivec2( 0, -1 ) : ivec2( -1, 0 );
		bool holdsBefore = cell.x + before.x < 0 || cell.y + before.y < 0 || warpAt( cell + before ) == warpTop;
		bool holdsAfter  = cell.x - before.x >= Grid.x || cell.y - before.y >= Grid.y || warpAt( cell - before ) == warpTop;

		float x = ( across - 0.5 ) / ( 0.5 * kWidth );
		float shade;
		vec3 sheen = vec3( 0.0 );
		if( abs( x ) > 1.0 )
		{
			//The gap between two threads: the other system, in shadow.
			colour = warpTop ? weftColour : Warp;
			shade  = 0.30;
		}
		else
		{
			float z       = sqrt( max( 1.0 - x * x, 0.0 ) );
			vec3 axis     = warpTop ? vec3( 0.0, 1.0, 0.0 ) : vec3( 1.0, 0.0, 0.0 );
			vec3 normal   = warpTop ? vec3( x, 0.0, z ) : vec3( 0.0, x, z );

			//Where a float ends the thread dives under the crossing thread:
			//its surface tilts away along its length and falls into shadow.
			float tilt = 0.0;
			if( !holdsBefore && along < kDip )
				tilt = -( 1.0 - along / kDip );
			if( !holdsAfter && along > 1.0 - kDip )
				tilt = ( along - ( 1.0 - kDip ) ) / kDip;
			normal = normalize( normal + axis * tilt * 0.9 );

			vec3 light   = normalize( kLight );
			float lambert = max( dot( normal, light ), 0.0 );
			float twist   = 1.0 - 0.10 * ( 0.5 + 0.5 * cos( 6.2831853 * ( along * kTwist - x * 0.45 ) ) );
			float hollow  = 1.0 - 0.35 * tilt * tilt;
			shade = kGain * ( 0.30 + 0.85 * lambert ) * twist * hollow;

			vec3 halfway = normalize( light + vec3( 0.0, 0.0, 1.0 ) );
			//The sheen is the thread's own colour, brightened: a black satin
			//shines, but only as black silk does, and a white sheen on it
			//would lift every shadow in the picture to grey.
			float spec   = pow( max( dot( normal, halfway ), 0.0 ), 28.0 ) * 0.35 * hollow;
			sheen        = spec * colour;
		}
		cloth = colour * mix( 1.0, shade, amount ) + amount * sheen;
	}

	//A cloth has no holes: opaque, whatever the clip's alpha.
	float opacity = ( Perturb & 128 ) != 0 ? source.a : 1.0;
	vec4 woven = vec4( encode( cloth.r ), encode( cloth.g ), encode( cloth.b ), opacity );
	fragColor  = mix( source, woven, MixAmount );
}
`;
//=== END GENERATED (shaders)

/// shaders::assemble: the version line, then the body.
const assemble = (body) => VERSION + body;

//===========================================================================
// The renderer: Jacquard::ProcessOpenGL, in its order.
//
//   1. cells      Ends x Picks, RGBA32F: each crossing's mean in linear light
//   2. read-back  readPixels as FLOAT
//   3. shuttles   the k-means of the crossings (Clip) or a swatch card
//   4. the loom   pick by pick, top to bottom; an Ends x Picks RG8 upload
//   5. render     the cloth as lit thread, onto the canvas
//===========================================================================

/// The k-means reads at most this many crossings a frame (Jacquard.cpp).
const K_PALETTE_SAMPLES = 16384;

/// What the line under the canvas reports. Filled by the renderer.
const telemetry = { ends: 0, picks: 0, shuttles: 0, programmes: 0, remembered: false, cpuMillis: 0, colours: [] };

/// Driven checks only (see AGENTS.md, "The browser demo"): `fresh()` puts the
/// renderer back to a new instance's state; `afterRender`, if set, is called
/// inside the frame with the GL context, so a script can read the canvas
/// before it is presented; `lastMeans` is the frame's read-back and
/// `lastCloth` what the ported loom wove from it.
const hooks = { afterRender: null, fresh: null, lastMeans: null, lastInput: null, lastCloth: null, lastShuttles: null };

function createRenderer(gl, quad) {
  const cellsShader = new Program(gl, assemble(VERTEX_BODY), assemble(CELLS_BODY), 'cells');
  const renderShader = new Program(gl, assemble(VERTEX_BODY), assemble(RENDER_BODY), 'render');
  const cells = new PassBuffer(gl, { filter: 'nearest' });

  // Ends x Picks RG8: R 255 where the warp is on top, G the pick's shuttle.
  const liftTexture = gl.createTexture();
  let liftEnds = 0;
  let liftPicks = 0;

  // The state across frames: the shuttles' k-means, the palette it was run
  // for, and the last cloth, which the next frame remembers.
  let kmeans = new L.KMeans();
  let lastPaletteSource = -1;
  let cloth = null;
  let means = new Float32Array(0);
  let liftBytes = new Uint8Array(0);

  hooks.fresh = () => {
    kmeans = new L.KMeans();
    lastPaletteSource = -1;
    cloth = null;
  };

  return {
    render({ input, params, width: vpW, height: vpH }) {
      // The host stores every parameter as a float.
      const p = (id) => Math.fround(params.get(id));
      const width = input.width;
      const height = input.height;
      hooks.lastInput = input;

      //------------------------------------------------------------------
      // What the controls say.
      //------------------------------------------------------------------
      const ends = L.ends(integerValue('ends', p('ends')));
      const aspect = L.threadAspect(p('threadAspect'));
      const picks = L.picks(integerValue('picks', p('picks')), ends, width, height, aspect);
      const maxFloat = L.maxFloat(integerValue('maxFloat', p('maxFloat')));
      const shuttleCount = L.shuttles(integerValue('shuttles', p('shuttles')));
      const source = L.optionIndex(p('palette'), L.SOURCE_COUNT);
      const mode = L.optionIndex(p('structure'), L.MODE_COUNT);
      const shading = Math.min(Math.max(p('shading'), 0), 1);
      const zoom = Math.fround(L.zoom(p('zoom')));
      const mixAmount = Math.min(Math.max(p('mix'), 0), 1);
      const warp = [L.toLinear(p('warpR')), L.toLinear(p('warpG')), L.toLinear(p('warpB'))];

      //------------------------------------------------------------------
      // Buffers.
      //------------------------------------------------------------------
      cells.ensure(ends, picks, gl.RGBA32F);
      if (ends !== liftEnds || picks !== liftPicks) {
        gl.bindTexture(gl.TEXTURE_2D, liftTexture);
        gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RG8, ends, picks, 0, gl.RG, gl.UNSIGNED_BYTE, null);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        gl.bindTexture(gl.TEXTURE_2D, null);
        liftEnds = ends;
        liftPicks = picks;
      }

      //------------------------------------------------------------------
      // 1. Cells: one linear mean per crossing.
      //------------------------------------------------------------------
      cells.bind();
      gl.disable(gl.BLEND);
      cellsShader.use();
      bindTexture(gl, 0, input.texture);
      cellsShader.setSampler('InputTexture', 0);
      gl.uniform2i(cellsShader.location('InputSize'), width, height);
      gl.uniform2i(cellsShader.location('Grid'), ends, picks);
      quad.draw();

      // Read them back: at most 320 x 320 x 4 floats. The one stall, and the
      // price of an encoder that is exact.
      if (means.length !== ends * picks * 4) means = new Float32Array(ends * picks * 4);
      gl.pixelStorei(gl.PACK_ALIGNMENT, 1);
      gl.readPixels(0, 0, ends, picks, gl.RGBA, gl.FLOAT, means);
      hooks.lastMeans = means;

      //------------------------------------------------------------------
      // 2. The shuttles, and the loom. CPU — here, the JavaScript port.
      //------------------------------------------------------------------
      const started = performance.now();
      if (source !== lastPaletteSource) kmeans.reset();
      lastPaletteSource = source;

      let shuttles;
      if (source === L.K_CLIP) {
        const count = ends * picks;
        kmeans.update(means, count, shuttleCount, Math.floor((count + K_PALETTE_SAMPLES - 1) / K_PALETTE_SAMPLES));
        shuttles = kmeans.centres.map((c) => c.slice());
      } else {
        shuttles = L.fixed(source, shuttleCount);
      }

      cloth = L.weave(means, { ends, picks, warp, shuttles, maxFloat, mode }, cloth);
      hooks.lastCloth = cloth;
      hooks.lastShuttles = shuttles;

      // uploadLift
      if (liftBytes.length !== ends * picks * 2) liftBytes = new Uint8Array(ends * picks * 2);
      for (let j = 0; j < picks; j += 1) {
        for (let i = 0; i < ends; i += 1) {
          const cell = j * ends + i;
          liftBytes[cell * 2] = cloth.lift[cell] ? 255 : 0;
          liftBytes[cell * 2 + 1] = cloth.weft[j];
        }
      }
      gl.bindTexture(gl.TEXTURE_2D, liftTexture);
      gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1);
      gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, ends, picks, gl.RG, gl.UNSIGNED_BYTE, liftBytes);
      gl.bindTexture(gl.TEXTURE_2D, null);

      telemetry.cpuMillis = performance.now() - started;
      telemetry.ends = ends;
      telemetry.picks = picks;
      telemetry.shuttles = shuttles.length;
      telemetry.programmes = cloth.programmes;
      telemetry.remembered = cloth.remembered;
      telemetry.colours = shuttles.map((c) => c.map(L.toEncoded));

      //------------------------------------------------------------------
      // 3. Render, onto the canvas. The host's viewport is the whole canvas.
      //------------------------------------------------------------------
      gl.bindFramebuffer(gl.FRAMEBUFFER, null);
      gl.viewport(0, 0, vpW, vpH);

      renderShader.use();
      bindTexture(gl, 0, liftTexture);
      bindTexture(gl, 1, input.texture);
      renderShader.setSampler('Lift', 0);
      renderShader.setSampler('Source', 1);
      renderShader.set('MaxUV', 1.0, 1.0);
      gl.uniform2i(renderShader.location('OutSize'), width, height);
      gl.uniform2i(renderShader.location('Grid'), ends, picks);
      renderShader.set('Warp', warp[0], warp[1], warp[2]);
      const packedShuttles = new Float32Array(L.MAX_SHUTTLES * 3);
      for (let k = 0; k < shuttles.length && k < L.MAX_SHUTTLES; k += 1) {
        packedShuttles[k * 3] = shuttles[k][0];
        packedShuttles[k * 3 + 1] = shuttles[k][1];
        packedShuttles[k * 3 + 2] = shuttles[k][2];
      }
      renderShader.setArray('Shuttle', packedShuttles, 3);
      renderShader.setInt('Shuttles', shuttles.length);
      renderShader.set('Zoom', zoom);
      renderShader.set('Shading', shading);
      renderShader.set('MixAmount', mixAmount);
      renderShader.setInt('Perturb', 0);
      quad.draw();

      if (hooks.afterRender) hooks.afterRender(gl, input);

      // Unbind so nothing reads a framebuffer's own texture next frame.
      bindTexture(gl, 1, null);
      bindTexture(gl, 0, null);
    },
  };
}

//===========================================================================
// The controls, read out of Jacquard::Jacquard(). Same names, same groups,
// same order, same defaults, same dropdown elements. Absent: the About block.
//===========================================================================

/// FF_TYPE_INTEGER is exempt from the 0..1 clamp, so the plugin stores these
/// as the integer itself. The kit has no integer control, so -- as teletext
/// and copperlist did -- they are dropdowns of every value in the plugin's
/// range; `integerValue` turns the dropdown's index back into it.
const C = L.CONTROLS_H;
const INTEGER_RANGES = {
  ends: [C.kEndsMin, C.kEndsMax],
  picks: [0, C.kPicksMax],
  maxFloat: [C.kMaxFloatMin, C.kMaxFloatMax],
  shuttles: [C.kShuttlesMin, C.kShuttlesMax],
};
const INTEGER_ELEMENTS = {};
for (const [id, [low, high]] of Object.entries(INTEGER_RANGES)) {
  INTEGER_ELEMENTS[id] = [];
  for (let v = low; v <= high; v += 1) INTEGER_ELEMENTS[id].push(String(v));
}
function integerValue(id, index) {
  const [low, high] = INTEGER_RANGES[id];
  return Math.min(high, Math.max(low, low + Math.round(index)));
}
const at = (id, value) => value - INTEGER_RANGES[id][0];

const integer = (id, name, value, group, hint) => ({ id, name, type: 'option', elements: INTEGER_ELEMENTS[id], default: at(id, value), group, hint });
const std = (id, name, def, group, extra = {}) => ({ id, name, type: 'standard', default: def, group, ...extra });
const opt = (id, name, elements, def, group, hint) => ({ id, name, type: 'option', elements, default: def, group, hint });
const colour = (id, name, def, group) => ({ id, name, type: 'colour', default: def, group });

const demo = mountDemo({
  name: 'Jacquard',
  pluginId: 'JQ01',
  kind: 'effect',
  tagline:
    'The picture woven on a jacquard loom. One warp colour, one weft colour a pick from the shuttles loaded, tone carried by weave structure — satin, twill, plain — and no float longer than the weaver allows. An exactly optimal programme weaves each pick, top to bottom as a loom does; the threads are drawn lit, so the cloth reads as thread up close and as the picture from across the room. The shaders here are the plugin’s own; the loom is a port of its C++.',
  repo: 'https://github.com/stoatworks-labs/jacquard',
  page: 'https://stoatworks-labs.com/software/jacquard/',

  // The stock sentence says "same maths", which is only half true here: the
  // shaders are the plugin's, the encoder between them is a port.
  blurb:
    'It is Jacquard’s own GLSL, ported from the repository to WebGL2, with the CPU half — the k-means that dyes the shuttles and the loom’s exact row programme — ported to JavaScript by hand; nothing checks that port but a reader. It runs on generated clips in this page, with the plugin’s own parameters and no install.',

  // The cells buffer is RGBA32F and read back as floats, as the plugin's is.
  needFloat: true,

  params: [
    integer('ends', 'Ends', C.kEndsDefault, 'Loom',
      'Warp threads across the frame, 16 to 320. Each is one column of crossings.'),
    integer('picks', 'Picks', 0, 'Loom',
      'Weft rows down the frame. 0 is Auto: as many as make each crossing Thread Aspect times as tall as it is wide. Set, it overrides Thread Aspect.'),
    std('threadAspect', 'Thread Aspect', 0.5, 'Loom', {
      display: (v) => `${L.threadAspect(Math.fround(v)).toFixed(2)} × an end`,
      hint: 'A pick’s height over an end’s width, 0.5 to 2 on a log scale, with Picks on Auto. It steepens or flattens the twill’s diagonal.',
    }),
    integer('maxFloat', 'Max Float', C.kMaxFloatDefault, 'Loom',
      'The longest run of crossings any thread may make on one side, warp or weft, face or back. Solids must be tied at least this often.'),

    colour('warpR', 'Warp Colour', 0.08, 'Threads'),
    colour('warpG', 'Warp_Green', 0.07, 'Threads'),
    colour('warpB', 'Warp_Blue', 0.07, 'Threads'),
    integer('shuttles', 'Shuttles', C.kShuttlesDefault, 'Threads',
      'Weft colours loaded, 2 to 8. Every pick is one of them across the whole width.'),
    opt('palette', 'Palette', L.SOURCE_NAMES, 0, 'Threads',
      'Clip dyes the shuttles from the picture (k-means in linear light, warm-started from the last frame); the others are fixed swatch cards, the first N of eight.'),
    opt('structure', 'Structure', L.MODE_NAMES, 0, 'Threads',
      'Which weaves tone may choose: Auto uses the solids, the satins and three twills; Plain only plain weave, so the picture is carried by the shuttles alone.'),

    std('shading', 'Thread Shading', 1.0, 'Look', {
      hint: 'The lit thread: a cylinder with a dip where a float ends, a ply twist and a sheen. It fades out below about four pixels a crossing, by design.',
    }),
    std('zoom', 'Zoom', 0.0, 'Look', {
      display: (v) => `${L.zoom(Math.fround(v)).toFixed(2)}×`,
      hint: '1 to 8 times about the frame centre, on a log scale. The cloth is woven at the grid and not re-woven for the zoom.',
    }),
    std('mix', 'Mix', 1.0, 'Look'),
  ],

  // Colour and flat regions are what a woven picture shows best; the bars and
  // the geometry card show the banding along the picks and the twill's
  // diagonal plainly.
  sources: ['scene', 'bars', 'grid', 'ramp', 'spot', 'detail'],

  // The plugin ships no factory presets. These are the page's own, expressed
  // entirely in the plugin's parameters and reachable with the controls.
  presets: {
    'Coarse cloth, 48 ends': { ends: at('ends', 48) },
    'Thread up close (4×)': { zoom: 2 / 3 },
    'Plain weave only': { structure: 1 },
    'Twills only, steep': { structure: 2, threadAspect: 1 },
    'Satins only': { structure: 3 },
    'Heritage dyes, eight': { palette: 1, shuttles: at('shuttles', 8) },
    'Two shuttles': { shuttles: at('shuttles', 2) },
    'Tightly tied (Max Float 2)': { maxFloat: at('maxFloat', 2) },
    'Undyed warp': { warpR: 0.9, warpG: 0.85, warpB: 0.72 },
  },

  differences: [
    'The CPU half of this plugin is a PORT, not the plugin’s own code. Jacquard reads one linear mean per crossing back to the CPU, dyes the shuttles by a farthest-point-seeded, warm-started k-means (Palette.cpp), and weaves the cloth pick by pick with an exact dynamic programme over each pick’s shuttle and lift pattern (Loom.cpp, Encoder.cpp, Weave.cpp). All of that is ported here to JavaScript, function for function, in loom.js, because without it the page would have no cloth to draw. Nothing checks a port but a reader; the repository’s jqtest checks the C++ against an exhaustive search and has never heard of this page.',
    'Measured against the C++ on fixed crossing means, at v0.1.0 and again at v0.1.1 (41 frames, nine grids from 16 × 9 to 320 × 320, black grounds crossed by bright picks, every palette and structure mode, a cold start mid-run): identical, bit for bit, to the C++ compiled for Intel. Against the Apple Silicon build, which fuses some float multiply-adds, the same cloth on every crossing of those frames, with the float costs rounding differently. The port rounds every float operation separately, as the Intel build does; on another picture a crossing whose choice sits on a knife edge could go the other way there.',
    'Measured end to end, at v0.1.0 and again at v0.1.1: this page’s own input frames piped through the plugin’s harness (jqtest --pipe, the real plugin class) gave the same picture as this page on every pixel of 18 frames (22 at v0.1.1) at the defaults and with the loom’s controls moved, and to within one 8-bit level with the Look controls moved or on a software GPU — on one Apple Silicon machine. That is a measurement of one machine on a few frames, not a guarantee for yours.',
    'The GPU half is not a port. The cells pass and the render pass are the plugin’s own GLSL, and demo/tools/check_shaders.py fails the repository’s verify script if a character of either shader (or the shared vertex shader) drifts. A browser’s GPU rounds the crossing means its own way, so the loom’s choices here can differ from Resolume’s by a crossing here and there.',
    'The crossing means are read back from the GPU with readPixels as floats every frame, exactly as the plugin’s glGetTexImage does, and stall the pipeline where it does.',
    'What the plugin claims, it claims here too, and no more. Each pick is exactly optimal given the picks above it; the cloth as a whole is not a two-dimensional optimum — weaving top to bottom is greedy between picks, and the error each crossing is left with is carried to the next pick. The float limit is enforced inside each pick: a warp end that has run Max Float picks on one side forbids that side at its next crossing. One weft colour a pick; there is no brocade or lampas mode. The output alpha is 1: a cloth has no holes.',
    'The loom remembers its last frame as small costs in each pick’s table, so a still clip holds still. It forgets when the grid, the shuttle count or the structure mode changes — and here also when the page reloads.',
    'Ends, Picks, Max Float and Shuttles are FF_TYPE_INTEGER in the plugin. The kit has no integer control, so they are dropdowns of every value in the plugin’s range.',
    'The plugin’s Perturb test hooks, its forced structure and its greedy weaver (negative controls for the harness) are not ported: none of them is part of what the plugin does in a host.',
    'There is no audio caveat and no clock caveat on this page: Jacquard has no audio path and reads no time.',
    'The plugin’s proof — every pick against an exhaustive search, no float past the limit, each structure’s exact weft ratio, the twill’s angle, one weft a pick, the distance to the picture — is an offline harness in the repository. Nothing on this page measures anything; the line under the canvas reports what the ported loom did.',
  ],

  createRenderer,
});

//---------------------------------------------------------------------------
// The line under the canvas: the ported loom's own numbers. Skipped in embed
// mode, where there is no reader.
//---------------------------------------------------------------------------
if (demo && !new URLSearchParams(window.location.search).has('embed')) {
  const stage = document.querySelector('.stage');
  if (stage) {
    const line = document.createElement('p');
    line.className = 'stage__status';
    line.dataset.loom = '';
    stage.append(line);
    const hex = (c) => `#${c.map((v) => Math.round(Math.min(Math.max(v, 0), 1) * 255).toString(16).padStart(2, '0')).join('')}`;
    let last = '';
    const update = () => {
      if (telemetry.ends > 0) {
        const text = `${telemetry.ends} × ${telemetry.picks} crossings · ${telemetry.shuttles} shuttles ${telemetry.colours.map(hex).join(' ')} · ${telemetry.programmes} row programmes for ${telemetry.picks} picks · ${telemetry.remembered ? 'remembering the last frame' : 'woven fresh'} · the JS loom took ${telemetry.cpuMillis.toFixed(1)} ms`;
        if (text !== last) {
          line.textContent = text;
          last = text;
        }
      }
      setTimeout(update, 250);
    };
    update();
  }
}

// For driven checks: the page's handle, the telemetry and the hooks.
window.__jacquardDemo = { demo, telemetry, hooks };
