"""Copy the plugin's shaders and constants into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the two generated blocks
    python3 demo/tools/sync_shaders.py --print  print them instead

Two regions, each between a `//=== BEGIN GENERATED by demo/tools/sync_shaders.py (<name>)`
line and its `//=== END GENERATED (<name>)` line, belong to this script:

  - `demo/plugin.js`, (shaders): the version line and the three GLSL bodies of
    `source/Shaders.cpp` (`kVertexBody`, `kCellsBody`, `kRenderBody`), each
    spliced into a JavaScript template literal with its tabs, its comments and
    its blank lines exactly as they are. A template literal cannot hold a raw
    backtick, a backslash or a `${`, so those three would be escaped (none of
    the shaders has one today) and `check_shaders.py` undoes exactly those three
    and refuses any other escape;
  - `demo/loom.js`, (constants): the constants of `source/Loom.h` (the costs and
    the memory terms), `source/Controls.h` (the ranges) and `source/Palette.h`,
    the two swatch cards of `source/Palette.cpp`, and the option names of
    `Palette.cpp`'s `SourceName` and `Weave.cpp`'s `ModeName`, each literal
    copied as the C++ spells it, less a float's `f` suffix.

What this script does NOT write is the port: everything else in loom.js, and
the frame sequence in plugin.js, is a hand translation of Controls.cpp,
Palette.cpp, Weave.cpp, Encoder.cpp, Loom.cpp and Jacquard::ProcessOpenGL, and
only a reader checks those.

Run it whenever a shader or one of those constants changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

# JS constant, C++ symbol in source/Shaders.cpp, in the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("CELLS_BODY", "kCellsBody"),
    ("RENDER_BODY", "kRenderBody"),
]

TARGETS = {
    "shaders": "demo/plugin.js",
    "constants": "demo/loom.js",
}


def begin(name):
    return f"//=== BEGIN GENERATED by demo/tools/sync_shaders.py ({name})"


def end(name):
    return f"//=== END GENERATED ({name})"


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def number(token):
    """A C++ numeric literal as JavaScript: drop a float's f suffix, nothing else."""
    token = token.strip()
    return re.sub(r"(?<=[0-9.])f\b", "", token)


def scalars(source, types):
    out = []
    for match in re.finditer(r"constexpr (" + types + r") (k\w+)\s*=\s*([^;{\[]+);", source):
        out.append((match.group(2), number(match.group(3))))
    if not out:
        raise SystemExit("no constants found where some were expected")
    return out


def swatches(palette_cpp, symbol):
    match = re.search(r"const Swatch " + symbol + r"\[ kMaxShuttles \] = \{(.*?)\n\};", palette_cpp, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Palette.cpp")
    rows = re.findall(r"\{([^}]*)\}", match.group(1))
    return [[number(v) for v in row.split(",")] for row in rows]


def names_of(source, function, count_symbol, where):
    match = re.search(
        function + r"\( int \w+ \)\s*\{\s*static const char\* const names\[ " + count_symbol + r" \] = \{ (.*?) \};",
        source,
        re.S,
    )
    if match is None:
        raise SystemExit(f"{function}'s names not found in {where}")
    return re.findall(r'"([^"]*)"', match.group(1))


def obj(pairs, indent="  "):
    return "{\n" + "".join(f"{indent}{k}: {v},\n" for k, v in pairs) + "}"


def js_rows(rows):
    return "[" + ", ".join("[" + ", ".join(r) + "]" for r in rows) + "]"


def js_strings(values):
    return "[" + ", ".join("'" + v.replace("'", "\\'") + "'" for v in values) + "]"


def shaders_block():
    shaders_cpp = read("source/Shaders.cpp")
    out = [begin("shaders") + " from source/Shaders.cpp -- do not edit by hand."]
    out.append(f"const VERSION = '{cpp_version(shaders_cpp)}';")
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")
    out[-1] = end("shaders")
    return "\n".join(out)


def constants_block():
    loom_h = read("source/Loom.h")
    controls_h = read("source/Controls.h")
    palette_h = read("source/Palette.h")
    palette_cpp = read("source/Palette.cpp")
    weave_cpp = read("source/Weave.cpp")

    out = [begin("constants") + " from source/ -- do not edit by hand."]
    out.append("// source/Loom.h")
    out.append("const LOOM_H = " + obj(scalars(loom_h, "double|float|int64_t|int")) + ";")
    out.append("// source/Controls.h")
    out.append("export const CONTROLS_H = " + obj(scalars(controls_h, "int")) + ";")
    out.append("// source/Palette.h")
    out.append("const PALETTE_H = " + obj(scalars(palette_h, "int")) + ";")
    out.append("// source/Palette.cpp: the swatch cards, sRGB.")
    out.append("const HERITAGE_SWATCHES = " + js_rows(swatches(palette_cpp, "kHeritageSwatches")) + ";")
    out.append("const BRIGHT_SWATCHES = " + js_rows(swatches(palette_cpp, "kBrightSwatches")) + ";")
    out.append("// The option lists: Palette.cpp SourceName, Weave.cpp ModeName.")
    out.append("export const SOURCE_NAMES = " + js_strings(names_of(palette_cpp, "SourceName", "kSourceCount", "source/Palette.cpp")) + ";")
    out.append("export const MODE_NAMES = " + js_strings(names_of(weave_cpp, "ModeName", "kModeCount", "source/Weave.cpp")) + ";")
    out.append(end("constants"))
    return "\n".join(out)


BLOCKS = {"shaders": shaders_block, "constants": constants_block}


def region(text, name):
    start = text.find(begin(name))
    stop = text.find(end(name))
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(end(name))


def main():
    if "--print" in sys.argv:
        for name in BLOCKS:
            print(BLOCKS[name]())
            print()
        return 0
    for name, path in TARGETS.items():
        full = os.path.join(REPO, path)
        with open(full) as handle:
            text = handle.read()
        where = region(text, name)
        if where is None:
            raise SystemExit(f"{path} has no ({name}) generated block")
        updated = text[: where[0]] + BLOCKS[name]() + text[where[1]:]
        if updated == text:
            print(f"{path}: the ({name}) block already matches source/")
            continue
        with open(full, "w") as handle:
            handle.write(updated)
        print(f"{path}: the ({name}) block rewritten from source/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
